### ISSUE TITLE
Use of JS reserved keyword 'for' in PaymentErrorHandler

### ISSUE THREAD

**Issue by pacovell** [FeeFighters/samurai-js#1]
// Samurai.PaymentErrorHandler.for(form).handleErrorsFromResponse(transaction);

This breaks capybara-webkit and (I suspect) any version of IE < 9, all of which aggressively enforce the non-usage of reserved ES/JS keywords (even if they are unused reserved keywords like 'class').

**Comment by pacovell** [comment]
Workaround:

``` javascript
      var errorHandler = new Samurai.PaymentErrorHandler('#payment form');

      ...
      errorHandler.handleErrorsFromResponse(transaction);
```

**Comment by tisho** [comment]
Thanks, @pacovell. The `for` method is now renamed to `forForm`, but your workaround is still valid.
