### ISSUE TITLE
Referencing with file:// causes browser errors

### ISSUE THREAD

**Issue by jkrall** [FeeFighters/samurai-js#3]
file:// urls trigger browser security, and cause the RPC calls fail with cryptic error messages like:

`Line 4: Uncaught TypeError: Cannot read property '2' of null`

We should consider adding a `window.location` check in `Samurai.init()` that spits out a nice warning if the script is loaded on a page that is being served up statically via file://

**Comment by tisho** [comment]
Closed in 55709068eff39153fb87b9d55244f5d99dbba833.
